{{- if .Values.storageclass.lvm.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.lvm.name }}
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}
parameters:
  {{- range $key, $value := .Values.storageclass.lvm.parameters }}
  {{ $key }}: {{ $value }}
  {{- end }}
reclaimPolicy: {{ .Values.storageclass.lvm.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageclass.lvm.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageclass.lvm.allowVolumeExpansion }}
{{- end }}

{{- if .Values.storageclass.lvm_xfs.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.lvm_xfs.name }}
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}
parameters:
  {{- range $key, $value := .Values.storageclass.lvm_xfs.parameters }}
  {{ $key }}: {{ $value }}
  {{- end }}
reclaimPolicy: {{ .Values.storageclass.lvm_xfs.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageclass.lvm_xfs.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageclass.lvm_xfs.allowVolumeExpansion }}
{{- end }}

{{- if .Values.storageclass.device_hdd.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.device_hdd.name }}
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}
parameters:
  {{- range $key, $value := .Values.storageclass.device_hdd.parameters }}
  {{ $key }}: {{ $value }}
  {{- end }}
reclaimPolicy: {{ .Values.storageclass.device_hdd.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageclass.device_hdd.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageclass.device_hdd.allowVolumeExpansion }}
{{- end }}

{{- if .Values.storageclass.device_ssd.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.device_ssd.name }}
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}
parameters:
  {{- range $key, $value := .Values.storageclass.device_ssd.parameters }}
  {{ $key }}: {{ $value }}
  {{- end }}
reclaimPolicy: {{ .Values.storageclass.device_ssd.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageclass.device_ssd.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageclass.device_ssd.allowVolumeExpansion }}
{{- end }}

{{- if .Values.storageclass.lvm_throttle.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.lvm_throttle.name }}
{{ include "local.labels" . | indent 2 }}
provisioner: local.csi.aliyun.com
parameters:
  {{- range $key, $value := .Values.storageclass.lvm_throttle.parameters }}
  {{ $key }}: {{ $value }}
  {{- end }}
reclaimPolicy: {{ .Values.storageclass.lvm_throttle.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageclass.lvm_throttle.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageclass.lvm_throttle.allowVolumeExpansion }}
{{- end }}

{{- if .Values.storageclass.lvm.enabled }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Values.storageclass.lvm.name }}
{{ include "local.labels" . | indent 2 }}
driver: {{ .Values.driver }}
deletionPolicy: Delete
parameters:
  csi.aliyun.com/readonly: "true"
  csi.aliyun.com/snapshot-initial-size: 4Gi
  csi.aliyun.com/snapshot-expansion-size: 1Gi
  csi.aliyun.com/snapshot-expansion-threshold: 50%
{{- end }}