name: open-local
namespace: kube-system
driver: local.csi.aliyun.com
customLabels: {}
images:
  local:
    image: openlocal/open-local
    tag: v0.8.0-alpha
  registrar:
    image: openlocal/csi-node-driver-registrar
    tag: v2.3.0
  provisioner:
    image: openlocal/csi-provisioner
    tag: v2.2.2
  resizer:
    image: openlocal/csi-resizer
    tag: v1.3.0
  snapshotter:
    image: openlocal/csi-snapshotter
    tag: v4.2.1
  snapshot_controller:
    image: openlocal/snapshot-controller
    tag: v4.2.1
agent:
  name: open-local-agent
  # This block device will be used to create as a Volume Group in every node
  # Open-Local does nothing if the device has been formatted or mountted
  device: /dev/vdb
  kubelet_dir: /var/lib/kubelet
  volume_name_prefix: local
  spdk: false
  # driver mode can be 'all' or 'node'
  # all: agent will start as csi controller and csi node
  # node: agent will start as csi node
  driverMode: node
  max_volumes_per_node: 256
extender:
  name: open-local-scheduler-extender
  # scheduling strategy: binpack/spread
  strategy: spread
  # scheduler extender http port
  port: 23000
  # you can also configure your kube-scheduler manually, see docs/user-guide/kube-scheduler-configuration.md to get more details
  init_job: true
controller:
  update_nls: "true"
storageclass:
  # lvm StorageClass
  lvm:
    enabled: true
    name: open-local-lvm
    parameters:
      volumeType: "LVM"
      csi.storage.k8s.io/fstype: ext4
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
  # lvm_xfs StorageClass
  lvm_xfs:
    enabled: true
    name: open-local-lvm-xfs
    parameters:
      volumeType: LVM
      csi.storage.k8s.io/fstype: xfs
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
  # lvm_throttle StorageClass
  lvm_throttle:
    enabled: true
    name: open-local-lvm-io-throttle
    parameters:
      volumeType: LVM
      # bps: "1048576"
      # iops: "1024"
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
  # device_ssd StorageClass
  device_ssd:
    enabled: true
    name: open-local-device-ssd
    parameters:
      csi.storage.k8s.io/fstype: ext4
      volumeType: Device
      mediaType: ssd
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: false
  # device_hdd StorageClass
  device_hdd:
    enabled: true
    name: open-local-device-hdd
    parameters:
      csi.storage.k8s.io/fstype: ext4
      volumeType: Device
      mediaType: hdd
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: false
monitor:
  # install grafana dashboard
  enabled: false
  # grafana namespace
  namespace: monitoring
global:
  RegistryURL: docker.io
  ImagePullPolicy: Always
