name: yoda
namespace: kube-system
driver: yodaplugin.csi.alibabacloud.com
customLabels: {}
images:
  local:
    image: openlocal/open-local
    tag: v0.8.0-alpha
  registrar:
    image: openlocal/csi-node-driver-registrar
    tag: v2.3.0
  provisioner:
    image: openlocal/csi-provisioner
    tag: v2.2.2
  resizer:
    image: openlocal/csi-resizer
    tag: v1.3.0
  snapshotter:
    image: openlocal/csi-snapshotter
    tag: v4.2.1
  snapshot_controller:
    image: openlocal/snapshot-controller
    tag: v4.2.1
agent:
  name: yoda-agent
  kubelet_dir: /var/lib/kubelet
  volume_name_prefix: yoda
  spdk: false
  driverMode: node
  max_volumes_per_node: 256
extender:
  name: yoda-scheduler-extender
  # scheduling strategy: binpack/spread
  strategy: spread
  # scheduler extender http port
  port: 23000
  # you can also configure your kube-scheduler manually, see docs/user-guide/kube-scheduler-configuration.md to get more details
  init_job: true
controller:
  update_nls: "false"
  framework_scheduler_names: ahe-scheduler
storageclass:
  # lvm StorageClass
  lvm:
    enabled: true
    name: yoda-lvm-default
    parameters:
      volumeType: "LVM"
      csi.storage.k8s.io/fstype: ext4
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
  # lvm_xfs StorageClass
  lvm_xfs:
    enabled: true
    name: yoda-lvm-xfs
    parameters:
      volumeType: LVM
      csi.storage.k8s.io/fstype: xfs
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
  # lvm_throttle StorageClass
  lvm_throttle:
    enabled: false
    name: yoda-lvm-io-throttle
    parameters:
      volumeType: LVM
      # bps: "1048576"
      # iops: "1024"
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
  # device_ssd StorageClass
  device_ssd:
    enabled: true
    name: yoda-device-ssd
    parameters:
      csi.storage.k8s.io/fstype: ext4
      volumeType: Device
      mediaType: ssd
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: false
  # device_hdd StorageClass
  device_hdd:
    enabled: true
    name: yoda-device-hdd
    parameters:
      csi.storage.k8s.io/fstype: ext4
      volumeType: Device
      mediaType: hdd
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: false
monitor:
  # install grafana dashboard
  enabled: false
  # grafana namespace
  namespace: monitoring
global:
  YodaSchedulerSvcIP: 10.96.0.4
  RegistryURL: ack-agility-registry.cn-shanghai.cr.aliyuncs.com
  NumOfMasters: 3
  ImagePullPolicy: Always
