name: Docker Image CI

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:

  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]


defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  generate-jobs:
    name: open-local-build
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        include:
          -
            name: open-local
            image: dongjiang1989/open-local
            file: ./hack/build/Dockerfile
            platforms: linux/amd64,linux/arm64

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - id: git-versions
        run: |
          echo "::set-output name=git-version::$(git describe --tags --always)"
      - id: git-branch
        run: |
          echo "::set-output name=git-branch::$(echo ${GITHUB_REF##*/} | tr '[A-Z]' '[a-z]')"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2 
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.file }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: |
            ${{ matrix.image }}:${{steps.git-branch.outputs.git-branch}}-${{steps.git-versions.outputs.git-version}}
            ${{ matrix.image }}:${{steps.git-branch.outputs.git-branch}}
      - name: Test ${{ matrix.name }}
        run: |
          docker pull ${{ matrix.image}}:${{steps.git-branch.outputs.git-branch}}-${{steps.git-versions.outputs.git-version}}
          docker image inspect ${{ matrix.image}}:${{steps.git-branch.outputs.git-branch}}-${{steps.git-versions.outputs.git-version}}
